name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0/600 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "17683137371@163.com"
          git config --local user.name "realsimmons123"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Good Lucky"
          git push
